[KIMI]
kimi_key = "sk-fDGsChYiGQjJsX6yLhuOU1i5SXjmobR4QJDPAbbSZUPztCQS"
kimi_base = "https://api.moonshot.cn/v1"

[DEEPSEEK]
deepseek_key = "sk-62efc71a7b434438a56647a74439beb1"
deepseek_base = "https://api.deepseek.com"

[CHATGLM]
chatglm_key = "e5abe90cbbc1231b7719bfcbbc2fe552.DMHUgId6Sv5Grh1e"
chatglm_base = "https://open.bigmodel.cn/api/paas/v4/chat/completions"

