[GENERATOR]
generator_model = [ "glm-4-flash", "moonshot-v1-8k", "deepseek-chat", "Qwen-Turbo", "Doubao-lite-32k", "generalv3.5",]
main_areas = [ "女士", "化妆品",]
needs = "给我写一份白桦树口红的营销文案"
key_words = "精致，精准色号"
character_style = [ "女大学生",]
language_style = [ "活泼", "专业", "温柔",]
